services:
  - type: web
    name: baseball-coaching
    runtime: python
    buildCommand: apt-get install -y ffmpeg && pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.0
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1
